# Generated by Django 4.2.5 on 2023-09-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotaStatistics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(verbose_name="login date")),
                ("is_linux", models.BooleanField(verbose_name="server type")),
                ("used", models.BigIntegerField(verbose_name="used size")),
                (
                    "dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.organisation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.employee"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quota",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("size", models.BigIntegerField(verbose_name="quota size")),
                ("is_linux", models.BooleanField(verbose_name="server type")),
                ("warning", models.BigIntegerField(verbose_name="warning quota size")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.employee"
                    ),
                ),
            ],
        ),
    ]
