# Generated by Django 4.2.5 on 2023-09-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quota", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quota",
            name="is_linux",
            field=models.BooleanField(verbose_name="server type(true for linux)"),
        ),
        migrations.AlterField(
            model_name="quotastatistics",
            name="is_linux",
            field=models.BooleanField(verbose_name="server type(true for linux)"),
        ),
    ]
