# Generated by Django 4.2.5 on 2023-09-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quota', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quota',
            old_name='user',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='quotastatistics',
            old_name='user',
            new_name='employee',
        ),
    ]
