# Generated by Django 4.2.5 on 2023-09-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("dept", models.CharField(max_length=10, verbose_name="department")),
                ("code", models.CharField(max_length=30, verbose_name="department id")),
                (
                    "description",
                    models.CharField(
                        max_length=255, verbose_name="department description"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="employee name"),
                ),
                (
                    "login",
                    models.CharField(max_length=255, verbose_name="user login id"),
                ),
                (
                    "onboard_date",
                    models.DateField(auto_now=True, verbose_name="onboard date"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.organisation",
                    ),
                ),
            ],
        ),
    ]
