# Generated by Django 4.2.5 on 2023-09-25 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quota", "0001_initial"),
        ("user", "0002_alter_employee_onboard_date"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Organisation",
            new_name="Organization",
        ),
    ]
